### PR TITLE
comprised of → composed of

### PR DESCRIPTION
**Pull request by bentley**

### CODE REVIEW

**Comment by acabal** [comment]
I think comprised is correct here

**Comment by bentley** [comment]
This is inverted from the traditional meaning; i.e., “comprising” would certainly be correct here. Whether “comprised” is too depends on one’s preferred level of descriptivism. I find a lot of arguments against “comprised of” convincing (such as [this essay](https://en.wikipedia.org/wiki/User:Giraffedata/comprised_of)), and since there are only two cases in SE descriptions, think they’re worth reconsidering.

**Comment by acabal** [comment]
M-W has definition 2 as in this sense, and even has a quote using it in the same sense: `about 8 percent of our military forces are comprised of women. --Jimmy Carter`

**Comment by bentley** [comment]
Yes, because dictionaries are by nature descriptive rather than prescriptive. But I won’t press this one further.

**Comment by acabal** [comment]
After some more thought, I changed my mind on this. I've fixed both of them in other commits and also added a lint check.

**Pull request closed without merging**
